export const songs = [
  "Aviscerall - Lullabyes",
  "Astroblk - nothing really matters that much to me anymore",
  "Lazy Vibes - Late Night Drive",
  "Aviscerall - The Hero is Defeated (feat. NetNavi)",
  "Astroblk - explorer",
  "Aviscerall - Sanctuary",
  "wood. - Adrift",
  "Lazy Vibes - Forest Walk",
  "Aviscerall - My Neighbor is a Cat",
  "Astroblk - vancouver",
  "NetNavi - mugen",
  "nanoshrine - Finding My Way Back to You",
  "NetNavi - Doublesoul",
  "Astroblk - rememberance",
  "Aviscerall - Coffee Shop",
  "Aviscerall - Healing",
  "Lazy Vibes - Summer Rain",
  "Astroblk - sunrise",
  "Astroblk - tumeric",
  "Datagirl - From Me to You",
  "Aviscerall - Alone at Sunset",
  "NetNavi - To a Song",
  "Astroblk - ginger spice",
  "Aviscerall - Remember the Time",
  "NetNavi - How Can You Tell",
  "Astroblk - cloudy days",
  "Aviscerall - Clockin' Out",
  "Astroblk - partir",
  "Aviscerall - Finding Home",
  "Astroblk - soul in seoul",
  "Astroblk - whirly",
  "Millennium Edition - Path Fragmentation",
  "NetNavi - Take a Trip",
  "nanoshrine - I Thought You Said You Were Fine",
  "Astroblk - Gold",
  "Astroblk - courage",
  "Aviscerall - Chillin",
  "Astroblk - shall we_",
  "Aviscerall - Feelings (feat. Of the Other Time & Alexis Luter)",
  "Astroblk - pay up",
  "Aviscerall - Romance",
  "Astroblk - chill groove 08 (16)",
  "Aviscerall - Sunkissed",
  "Astroblk - onde vamos",
  "Astroblk - vveirdness",
  "Aviscerall - Sheep Song",
  "Astroblk - SG03",
  "Astroblk - geneva",
  "Aviscerall - Onett"
];
